version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
cache:
  paths:
    - node_modules/**/*
artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json
    - ormconfig.json